### PR TITLE
Adds Kokoro build scripts.

### LINKED ISSUE #43: kokoro config
Build and release with kokoro

### PR DESCRIPTION
**Pull request by coollog**
Fixes #43 .

Also updates versioning of endpoints plugins to fix broken tests.

### CODE REVIEW

**Comment by coollog** [comment]
The build seems to be breaking. A new version (2.0.9) of endpoints-framework-tools was released. I think some new change there might have caused this.

**Comment by loosebazooka** [comment]
Yeah I think the google api client needs to be updated to 1.23 in https://github.com/GoogleCloudPlatform/endpoints-framework-maven-plugin/blob/master/src/test/resources/projects/client/pom.xml#L40

**Comment by coollog** [comment]
Okay, this should be all good now.

**Comment by coollog** [comment]
The Kokoro build succeeds but the artifact doesn't seem to be written to the bucket..

**Pull request merged**
